### ISSUE TITLE
Can't install `parsevasp==0.4.1`

### ISSUE THREAD

**Issue by yakutovicha** [espenfl/parsevasp#22]
I was trying to install `parsevasp==0.4.1` on AiiDA lab docker container. However, I got the following error:

```
Collecting parsevasp==0.4.1 (from aiidalab==19.5.3)
  Downloading https://files.pythonhosted.org/packages/20/ab/c3a7de645bcdf44040837b07a664c25345028bc8d6f724eb26134021e3ec/parsevasp-0.4.1.tar.gz (70kB)
    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/python2.7.15/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-TyXeL3/parsevasp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-TyXeL3/parsevasp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-TyXeL3/parsevasp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-TyXeL3/parsevasp/setup.py", line 18, in <module>
        with open(SETUP_JSON_PATH, 'r') as info:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-TyXeL3/parsevasp/setup.json'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command "pip install -e ." failed and exited with 1 during .
```

Looks like the file `setup.json` is missing in the pypi package.

**Comment by espenfl** [comment]
Thanks for reporting @yakutovicha. Indeed, the `setup.json` was missing from the manifest. Added now, in https://github.com/espenfl/parsevasp/pull/23. New version `0.4.2` is uploaded.
